# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-17 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180118_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['address']},
        ),
    ]
