# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-15 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180115_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\u5206\u7c7b', 'verbose_name_plural': '\u5206\u7c7b\u5217\u8868'},
        ),
    ]
