# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-15 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180115_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name='\u5185\u5bb9'),
        ),
    ]
